### ISSUE TITLE
Unable to load the package in Chrome.

### ISSUE THREAD

**Issue by Trex187** [cldevdad/hit-spooner#3]
I have cloned the repository and installed yarn.  Whenever I run yarn, a command window opens and closes quickly. I've tried just loading the cloned repository directly to chrome but I get an error.  Any help would be appreciated.  Thanks for your time.

**Comment by cldevdad** [comment]
Hi, thanks for writing an issue! I am not sure what's going on, but I have removed the requirement for yarn version 4.x. I'm working on getting a build stage set up in GitHub and hopefully this is approved on the web store soon. The only thing I can think of is make sure you are running yarn in the folder you cloned to.

For now, until I get the CI set up, I've uploaded a branch that contains the built extension. This is the folder to install unpacked in Chrome Extensions if you just want to use HitSpooner:

https://github.com/cldevdad/hit-spooner/tree/cp/chore/binaries/dist

**Comment by cldevdad** [comment]
Hello, I'm happy to announce you may now install it from the store: https://chromewebstore.google.com/detail/hitspooner/plnjommomanicfmokelokhccfmomfppo.

If you are attempting development and are still runing into issues locally, please re-open the ticket.
